### ISSUE TITLE
Multimeter -- Slider -- Custom Element does not exist: Layout Card

### ISSUE THREAD

**Issue by rchadgray** [snootched/cb-lcars#13]
The Gauge Type works fine.  I just get this error when trying the Slider version of the Multimeter.

![image](https://github.com/user-attachments/assets/3e33c8e2-60af-4e6a-8cea-db855dbc805e)

**Comment by snootched** [comment]
Hi there - custom layout card is currently a requirement (listed in the dependcies section)
You can grab it from HACS / https://github.com/thomasloven/lovelace-layout-card

Once this card is there, the slider mode will render.

This dependency will be gone the next version as that whole part is being rewritten now.

**Comment by rchadgray** [comment]
Thank you!  I must have missed that.. but i found it and installed it.
