### ISSUE TITLE
HACS - Custom Brand Icons - Completely breaks cb_lcars

### ISSUE THREAD

**Issue by sereg-ur** [snootched/cb-lcars#6]
FYI - I am just starting to play with cb_lcars and I had everything up and running, but right after I installed the "Custom Brand Icons" from HACS, cb_lcars completely broke.
https://github.com/elax46/custom-brand-icons/tree/2024.11.1

After uninstalling this addon, cb_lcars started working fine again.

Example errors:
this._card.setConfig is not a function
Custom element doesn't exist: cblcars-button-card.

I noticed the following errors in the browser debug tools.

Loading failed for the <script> with source “https://_[home assistant url]_/hacsfiles/custom-brand-icons/762.cb-lcars.js”
Loading failed for the <script> with source “https://_[home assistant url]_/hacsfiles/custom-brand-icons/312.cb-lcars.js”.

Notice that it appears to be trying to load the cb_lcars.js from this other addon's folder.  I'm guessing there is a relative path issue somewhere.

This is not a pressing issue by any means.  I just thought it might help in case other addons start causing conflicting issues.
It may also not be an issues with your code, but rather theirs.  I figured you might want to be aware.

**Comment by snootched** [comment]
Thanks for your report - I see this as well (different card, same effect.)  This has to do with the way I have webpack configured and I'm working on this now and hopefully will fix this asap.

**Comment by snootched** [comment]
This chunk error shold be resolved now with the latest version.  The conflicting 'my-slider-v2' is external dependency again so this error should be corrected.
